export enum TypeGarantie {
  BIEN_IMMOBILIER = 'BIEN_IMMOBILIER',
  TERRAIN = 'TERRAIN',
  MAISON = 'MAISON',
  COMMERCE = 'COMMERCE',
  
  BIEN_MOBILIER = 'BIEN_MOBILIER',
  VEHICULE = 'VEHICULE',
  EQUIPEMENT = 'EQUIPEMENT',
  MATERIEL = 'MATERIEL',
  
  GARANTIE_PERSONNEL = 'GARANTIE_PERSONNEL',
  CAUTION_SOLIDAIRE = 'CAUTION_SOLIDAIRE',
  HYPOTHEQUE = 'HYPOTHEQUE',
  GAGE = 'GAGE',
  
  TITRE_FINANCIER = 'TITRE_FINANCIER',
  DEPOT_ESPECES = 'DEPOT_ESPECES',
  DEPOT_LIVRET = 'DEPOT_LIVRET',
  
  AUTRE = 'AUTRE'
}

export enum StatutGarantie {
  ACTIF = 'ACTIF',
  EN_ATTENTE = 'EN_ATTENTE',
  REALISEE = 'REALISEE',
  LIBEREE = 'LIBEREE',
  SAISIE = 'SAISIE'
}
