CREATE TABLE remboursement_apport_proprietaire (
    id BIGINT NOT NULL AUTO_INCREMENT,
    reference VARCHAR(50) NOT NULL,
    antenne_id BIGINT NOT NULL,
    montant DECIMAL(18,2) NOT NULL,
    statut VARCHAR(30) NOT NULL,
    motif_demande TEXT NULL,
    demande_par_id BIGINT NULL,
    date_demande DATETIME NOT NULL,
    valide_par_id BIGINT NULL,
    date_validation DATETIME NULL,
    motif_validation TEXT NULL,
    paye_par_id BIGINT NULL,
    date_paiement DATETIME NULL,
    operation_caisse_id BIGINT NULL,
    commentaire TEXT NULL,
    date_creation DATETIME NOT NULL,
    date_modification DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_remboursement_apport_reference (reference),
    KEY idx_remboursement_apport_statut (statut),
    KEY idx_remboursement_apport_antenne (antenne_id),
    KEY idx_remboursement_apport_operation (operation_caisse_id),
    CONSTRAINT fk_remboursement_apport_antenne FOREIGN KEY (antenne_id) REFERENCES agence(id),
    CONSTRAINT fk_remboursement_apport_demande_par FOREIGN KEY (demande_par_id) REFERENCES utilisateur(id),
    CONSTRAINT fk_remboursement_apport_valide_par FOREIGN KEY (valide_par_id) REFERENCES utilisateur(id),
    CONSTRAINT fk_remboursement_apport_paye_par FOREIGN KEY (paye_par_id) REFERENCES utilisateur(id),
    CONSTRAINT fk_remboursement_apport_operation FOREIGN KEY (operation_caisse_id) REFERENCES operation_caisse(id)
);
