DELETE FROM permissions
WHERE CAST(code AS CHAR) = ''
  AND LOWER(description) LIKE '%ticket%';

ALTER TABLE permissions MODIFY COLUMN code ENUM(
    'AGENT_TERRAIN_READ','ANALYSE_RISQUE_CREATE','ANALYSE_RISQUE_READ','AUDIT_LOG_EXPORT','AUDIT_LOG_READ','AUDIT_READ','AUDIT_SECURITY_READ',
    'CAISSE_CREATE','CAISSE_READ','CONTROLEUR_AUDIT_READ','CONTROLEUR_CREDITS_VALIDATE','CONTROLEUR_CREDIT_READ','CONTROLEUR_DEMANDE_CREDIT_READ',
    'CONTROLEUR_DEMANDE_CREDIT_VALIDATE','CONTROLEUR_ECART_READ','CONTROLEUR_ECART_VALIDATE','CONTROLEUR_EPARGNE_OPERATION_READ',
    'CONTROLEUR_EPARGNE_READ','CONTROLEUR_RECETTES_VALIDATE','CONTROLEUR_RETRAITS_VALIDATE','CONTROLEUR_SESSION_CAISSE_READ',
    'CONTROLEUR_SESSION_CAISSE_VALIDATE','CREDIT_APPROVE','CREDIT_DISBURSE','CREDIT_PRE_ANALYSE','CREDIT_READ','DASHBOARD_CAISSE_READ',
    'DASHBOARD_CONTROLE_INTERNE_READ','DASHBOARD_GLOBAL_READ','DEMANDE_CREDIT_CREATE','DEMANDE_CREDIT_READ','DEPENSE_CAISSE_CANCEL',
    'DEPENSE_CAISSE_CREATE','DEPENSE_CAISSE_PAY','DEPENSE_CAISSE_READ','DEPENSE_CAISSE_REJECT','DEPENSE_CAISSE_SUBMIT','DEPENSE_CAISSE_VALIDATE',
    'EPARGNE_COMPTE_CREATE','EPARGNE_COMPTE_READ','EPARGNE_OPERATION_CREATE','EPARGNE_OPERATION_READ','FICHE_JOURNALIERE_CREATE',
    'FICHE_JOURNALIERE_DELETE','FICHE_JOURNALIERE_EDIT','FICHE_JOURNALIERE_READ','GARANTIE_BLOQUER_EPARGNE','GARANTIE_CONTROL',
    'GARANTIE_MATERIELLE_CREATE','GARANTIE_READ','GARANTIE_VALIDATE','JOURNAL_CAISSE_READ','MEMBRE_CLOSE','MEMBRE_CREATE','MEMBRE_READ',
    'MEMBRE_READ_SELF','MEMBRE_UPDATE','MEMBRE_UPDATE_SELF','OPERATION_CAISSE_CREATE','OPERATION_CAISSE_READ','PERFORMANCE_TERRAIN_READ',
    'RAPPORT_CAISSE_AUDIT_READ','RAPPORT_CAISSE_EXPORT','RAPPORT_CAISSE_READ','RECLAMATION_COMMENT','RECLAMATION_READ','REMBOURSEMENT_CREATE',
    'REMBOURSEMENT_READ','SESSION_CAISSE_ADMIN_CANCEL','SESSION_CAISSE_ANOMALIE_READ','SESSION_CAISSE_ANOMALIE_REQUEST',
    'SESSION_CAISSE_ANOMALIE_VALIDATE','SESSION_CAISSE_CLOSE','SESSION_CAISSE_CONTROL_VALIDATE','SESSION_CAISSE_FINAL_CLOSE','SESSION_CAISSE_OPEN',
    'SESSION_CAISSE_OPEN_OVERRIDE','SESSION_CAISSE_PRE_CLOSE','SESSION_CAISSE_REOPEN_CONTROLLED','SITE_READ','TASK_AUDIT','TASK_COMPLETE',
    'TASK_READ_ANTENNE','TASK_READ_OWN','TASK_SUPERVISE','TERRAIN_ACTIVITY_READ','USER_ASSIGN_ROLE','USER_CREATE','USER_LOCK','USER_PASSWORD_CHANGE',
    'USER_PASSWORD_RESET','USER_READ','USER_UNLOCK','USER_UPDATE','TICKET_RECU_READ','TICKET_RECU_PRINT','TICKET_RECU_DUPLICATA','TICKET_RECU_VERIFY','TICKET_RECU_ADMIN'
) NOT NULL;

INSERT IGNORE INTO permissions (code, description, is_active, date_creation)
VALUES
    ('TICKET_RECU_READ', 'Consulter les tickets recus', TRUE, NOW()),
    ('TICKET_RECU_PRINT', 'Imprimer ou marquer impression ticket recu', TRUE, NOW()),
    ('TICKET_RECU_DUPLICATA', 'Generer un duplicata de ticket recu', TRUE, NOW()),
    ('TICKET_RECU_VERIFY', 'Verifier authenticite ticket recu', TRUE, NOW()),
    ('TICKET_RECU_ADMIN', 'Administrer les tickets recus', TRUE, NOW());

ALTER TABLE ticket_recu ENGINE = InnoDB;

ALTER TABLE ticket_recu
    ADD CONSTRAINT fk_ticket_original FOREIGN KEY (original_ticket_id) REFERENCES ticket_recu(id),
    ADD CONSTRAINT fk_ticket_operation_epargne FOREIGN KEY (operation_epargne_id) REFERENCES operation_epargne(id),
    ADD CONSTRAINT fk_ticket_operation_caisse FOREIGN KEY (operation_caisse_id) REFERENCES operation_caisse(id),
    ADD CONSTRAINT fk_ticket_operation_caisse_commission FOREIGN KEY (operation_caisse_commission_id) REFERENCES operation_caisse(id),
    ADD CONSTRAINT fk_ticket_demande_retrait FOREIGN KEY (demande_retrait_epargne_id) REFERENCES demande_retrait_epargne(id),
    ADD CONSTRAINT fk_ticket_collecte_journaliere FOREIGN KEY (collecte_journaliere_id) REFERENCES collecte_journaliere_terrain(id),
    ADD CONSTRAINT fk_ticket_collecte_ligne FOREIGN KEY (collecte_membre_ligne_id) REFERENCES collecte_membre_ligne(id),
    ADD CONSTRAINT fk_ticket_session_caisse FOREIGN KEY (session_caisse_id) REFERENCES session_caisse(id),
    ADD CONSTRAINT fk_ticket_caisse FOREIGN KEY (caisse_id) REFERENCES caisse(id),
    ADD CONSTRAINT fk_ticket_membre FOREIGN KEY (membre_id) REFERENCES membre(id),
    ADD CONSTRAINT fk_ticket_compte FOREIGN KEY (compte_epargne_id) REFERENCES compte_epargne(id),
    ADD CONSTRAINT fk_ticket_agence FOREIGN KEY (agence_id) REFERENCES agence(id),
    ADD CONSTRAINT fk_ticket_site FOREIGN KEY (site_id) REFERENCES site(id),
    ADD CONSTRAINT fk_ticket_utilisateur_createur FOREIGN KEY (utilisateur_createur_id) REFERENCES utilisateur(id),
    ADD CONSTRAINT fk_ticket_utilisateur_impression FOREIGN KEY (utilisateur_impression_id) REFERENCES utilisateur(id),
    ADD CONSTRAINT fk_ticket_utilisateur_duplicata FOREIGN KEY (utilisateur_duplicata_id) REFERENCES utilisateur(id),
    ADD CONSTRAINT fk_ticket_created_by FOREIGN KEY (created_by) REFERENCES utilisateur(id),
    ADD CONSTRAINT fk_ticket_updated_by FOREIGN KEY (updated_by) REFERENCES utilisateur(id);
