package com.mini.credit.enums.workflow;

public enum WorkflowTaskTypeAction {
	PRE_CLOTURER_SESSION_CAISSE,
    CONTROLER_SESSION_CAISSE,
    CLOTURER_SESSION_CAISSE,
    EFFECTUER_BILLETAGE,
    CONTROLER_RECETTE_TERRAIN,
    VALIDER_RETRAIT_EPARGNE,
    PAYER_RETRAIT_EPARGNE,
    TRAITER_DEMANDE_CREDIT,
    CONTROLER_DEMANDE_CREDIT,
    APPROUVER_DEMANDE_CREDIT,
    DECAISSER_CREDIT,
    DEPENSE_CAISSE_VALIDATE,
    DEPENSE_CAISSE_PAY
}
