export enum ActionAudit {
  SESSION_CAISSE_OPENED = 'SESSION_CAISSE_OPENED',
  SESSION_CAISSE_CLOSED = 'SESSION_CAISSE_CLOSED',
  OPERATION_CAISSE_CREATED = 'OPERATION_CAISSE_CREATED',
  DEPENSE_CAISSE_CREATED = 'DEPENSE_CAISSE_CREATED',
  DEPENSE_CAISSE_SUBMITTED = 'DEPENSE_CAISSE_SUBMITTED',
  DEPENSE_CAISSE_VALIDATED = 'DEPENSE_CAISSE_VALIDATED',
  DEPENSE_CAISSE_REJECTED = 'DEPENSE_CAISSE_REJECTED',
  DEPENSE_CAISSE_PAID = 'DEPENSE_CAISSE_PAID',
  DEPENSE_CAISSE_CANCELLED = 'DEPENSE_CAISSE_CANCELLED',
  OUVERTURE_SESSION = 'OUVERTURE_SESSION',
  PRE_CLOTURE = 'PRE_CLOTURE',
  VALIDATION_CONTROLE = 'VALIDATION_CONTROLE',
  CLOTURE_FINALE = 'CLOTURE_FINALE',
  REFUS_TRANSITION = 'REFUS_TRANSITION',
  MODIFICATION_OPERATION = 'MODIFICATION_OPERATION',
  ANNULATION_OPERATION = 'ANNULATION_OPERATION',
  DATA_EXPORT = 'DATA_EXPORT',
  RAPPORT_GENERE = 'RAPPORT_GENERE',
  ACCESS_DENIED = 'ACCESS_DENIED',
  INVALID_OPERATION = 'INVALID_OPERATION'
}

export enum AuditModule {
  CAISSE = 'CAISSE',
  SESSION_CAISSE = 'SESSION_CAISSE',
  OPERATION_CAISSE = 'OPERATION_CAISSE',
  DEPENSE_CAISSE = 'DEPENSE_CAISSE',
  JOURNAL_CAISSE = 'JOURNAL_CAISSE',
  RAPPORT_CAISSE = 'RAPPORT_CAISSE',
  RETRAIT_EPARGNE = 'RETRAIT_EPARGNE',
  CREDIT = 'CREDIT',
  RECETTE_TERRAIN = 'RECETTE_TERRAIN',
  PARAMETRAGE = 'PARAMETRAGE',
  AUTHENTIFICATION = 'AUTHENTIFICATION',
  CONTROLE_INTERNE = 'CONTROLE_INTERNE'
}

export enum SeveriteLog {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL'
}
