package com.mini.credit.service;

import com.mini.credit.dto.caisse.RecetteJournaliereTerrainDTO;

/**
 * PHASE 6B.2: Service for auto-generating operations from validated receipts.
 *
 * When RecetteJournaliereTerrain is validated (status = VALIDEE),
 * automatically generate:
 *   - OperationEpargne (DEPOT, REMBOURSEMENT_CREDIT, INTERET)
 *   - OperationCaisse (DEPOT, FRAIS)
 *   - CompteEpargne (if new member)
 *   - Update SessionCaisse
 *
 * Transaction: SERIALIZABLE isolation for consistency
 */
public interface RecetteOperationGenerationService {

    /**
     * Generate operations from a validated receipt.
     * 
     * Workflow (8 phases):
     * 1. Pre-generation validation (status, variance, cashRemis)
     * 2. Start SERIALIZABLE transaction
     * 3. Pre-generate: CompteEpargne if needed, find Credit if needed
     * 4. Generate operations by type (DEPOT, REMBOURSEMENT, etc)
     * 5. Link operations to receipt (recette_id FK)
     * 6. Update active SessionCaisse (totals)
     * 7. Audit logging
     * 8. Return summary
     * 
     * Idempotence: Check if operations already generated by referenceExterne
     *
     * @param recetteId Receipt to process
     * @return DTO with operation generation summary
     */
    OperationGenerationSummaryDTO generateOperationsFromReceipt(Long recetteId);

    /**
     * Summary DTO returned after generation
     */
    class OperationGenerationSummaryDTO {
        public Long recetteId;
        public boolean success;
        public int operationEpargneCount;
        public int operationCaisseCount;
        public String message;
        
        public OperationGenerationSummaryDTO(Long recetteId, boolean success, 
                                              int opEpargneCount, int opCaisseCount, String msg) {
            this.recetteId = recetteId;
            this.success = success;
            this.operationEpargneCount = opEpargneCount;
            this.operationCaisseCount = opCaisseCount;
            this.message = msg;
        }
    }
}
