import { DepenseCaisseCategorie } from './depense-caisse-categorie';
import { DepenseCaisseStatus } from './depense-caisse-status';
import { ModeCalculPaie } from './paie-employe-preview';
import { TypePaiementPersonnel } from './type-paiement-personnel';

export interface DepenseCaisseResponse {
  id: number;
  sessionCaisseId?: number;
  caisseId: number;
  caisseCode?: string;
  siteId?: number;
  siteNom?: string;
  categorie: DepenseCaisseCategorie;
  montant: number;
  devise: string;
  motif: string;
  beneficiaire?: string;
  beneficiaireId?: number;
  beneficiaireNom?: string;
  beneficiaireRole?: string;
  beneficiaireAgence?: string;
  employeId?: number;
  employeMatricule?: string;
  employeNomComplet?: string;
  employePoste?: string;
  salaireBase?: number;
  primeFixe?: number;
  bonusVariable?: number;
  periodePaie?: string;
  typePaiementPersonnel?: TypePaiementPersonnel;
  montantRemunerationReference?: number;
  montantEcartRemuneration?: number;
  motifEcartRemuneration?: string;
  naturePaiementPaie?: string;
  montantSalaireDu?: number;
  montantDejaPaye?: number;
  montantRestantApresPaiement?: number;
  montantRetenue?: number;
  motifRetenue?: string;
  motifPaiementPartiel?: string;
  commentairePaie?: string;
  epargneCollecteeReference?: number;
  remboursementCollecteReference?: number;
  nombreCarnetsVendus?: number;
  primeMobilisationEpargne?: number;
  primeMobilisationRemboursement?: number;
  bonusCarnets?: number;
  primeMotivationManuelle?: number;
  motifPrimeMotivationManuelle?: string;
  modeCalculPaie?: ModeCalculPaie;
  detailCalculPaieJson?: string;
  justificatifUrl?: string;
  statut: DepenseCaisseStatus;
  demandeParId?: number;
  demandeParNom?: string;
  valideParId?: number;
  valideParNom?: string;
  payeParId?: number;
  payeParNom?: string;
  dateDemande: string;
  dateSoumission?: string;
  dateValidation?: string;
  datePaiement?: string;
  operationCaisseId?: number;
  commentaireValidation?: string;
  motifRejet?: string;
  createdAt: string;
  updatedAt: string;
}