package com.mini.credit.enums;

public enum CategorieOperationCaisse {

    COTISATION,
    EPARGNE,
    RETRAIT_EPARGNE,
    FRAIS_DEMANDE,
    DEPOT_GARANTIE,
    DECAISSEMENT_CREDIT,
    REMBOURSEMENT_CREDIT,
    PENALITE_RETARD,
    APPROVISIONNEMENT,
    DEPENSE,
    ENTREE_DIVERSE,
    SORTIE_DIVERSE,
    REMBOURSEMENT_APPORT_PROPRIETAIRE,
    FRAIS_DEMANDE_CREDIT,
    FRAIS_RETRAIT_EPARGNE,
    DEPOT_GARANTIE_CREDIT
}
