package com.mini.credit.enums;

public enum TypeAnomalieSessionCaisse {
    OUVERTURE_ERRONEE_SANS_MOUVEMENT,
    PRE_CLOTURE_ERRONEE,
    CLOTURE_ERRONEE_SANS_MOUVEMENT,
    SESSION_AVEC_MOUVEMENTS_RECTIFICATION_REQUISE
}
