export type StatutDemandeCredit =
  | 'BROUILLON'
  | 'SOUMISE'
  | 'EN_ANALYSE'
  | 'ANALYSE_TERRAIN_VALIDEE'
  | 'VALIDATION_CHEF'
  | 'VALIDATION_CONTROLEUR'
  | 'APPROUVEE'
  | 'REJETEE'
  | 'ANNULEE';

export const STATUT_DEMANDE_CREDIT_OPTIONS: StatutDemandeCredit[] = [
  'BROUILLON',
  'SOUMISE',
  'EN_ANALYSE',
  'ANALYSE_TERRAIN_VALIDEE',
  'VALIDATION_CHEF',
  'VALIDATION_CONTROLEUR',
  'APPROUVEE',
  'REJETEE',
  'ANNULEE'
];